title: "CYBERTEST"
description: "GitHub Pages Test"
baseurl: "/test-repo"
url: "https://qw84.github.io"

markdown: kramdown
permalink: /:year/:title/

plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:year/:title/

defaults:
  - scope:
      path: "projects.html"
    values:
      layout: page
      title: Projects
      tags: []
  - scope:
      path: "posts.html"
    values:
      layout: page
      title: Posts
      tags: []